### ISSUE TITLE
Composer paketinin bulunmaması

### ISSUE THREAD

**Issue by onurozgurozkan** [bulutfon/bulutfon-whmcs#11]
Merhaba,

Kurulum esnasında bir çok kullanıcı composer paketini kullanmayı bilmiyor. Acaba composer paketini de içeren bir versiyonun indirme linkini eklenirse nasıl olur?

http://devforums.bulutfon.com/t/whmcs-eklentisi-v0-1-6-hooks-hatasi/91

Kolay gelsin.

**Comment by hakanersu** [comment]
Aslinda su an gerekli kutuphaneler ekli olarak paketledim.

**Comment by onurozgurozkan** [comment]
+1
