### ISSUE TITLE
Whmcs versiyon desteği

### ISSUE THREAD

**Issue by onurozgurozkan** [bulutfon/bulutfon-whmcs#12]
@hakanersu Merhaba,

Eklenti WHMCS'nin hangi sürümlerine destek veriyor? 5.x'e destek vermiyor diye hatırlıyorum. 

Kolay gelsin.

**Comment by hakanersu** [comment]
WHMCS 6+ destek verilmekte. 5.x den 6'a oldukca buyuk altyapi degisiklikleri yapildi.
