### ISSUE TITLE
whmcs version 7+ güncelleme

### ISSUE THREAD

**Issue by yk-labs** [bulutfon/bulutfon-whmcs#20]
merhaba hakan bey, whmcs version 7+ güncelleme hazırlayabilirseniz sevinirim. şimdiden teşekkür ederim

**Comment by hakanersu** [comment]
Fırsat bulabilirsem yakın zamanda ilgilenmeye çalışacağım.

**Comment by yk-labs** [comment]
teşekkür ederim

**Comment by MtAydemir** [comment]
Whmcs 7 de çalışırken bir sorun görünmüyor ancak Whmcs nin dahili Auto Update aracıyla çakışma yapıyor. Bu yüzden manuel update yapmak zorunda kalıyorsunuz.

Alınan update hatası:

rror (Help Documentation)
Error: Argument 1 passed to GuzzleHttp\Ring\Client\StreamHandler::__invoke() must be of the type array, object given, called in /home/------/public_html/modules/addons/bulutfon/vendor/guzzlehttp/guzzle/src/Client.php on line 268 and defined
[ErrorException]
File hash was validated. Hash: ------------------------------------------------------------------------------------------------------
Validating /home/-----/public_html/vendor/whmcs/whmcs/----------------------------------------.zip
Downloading
- Installing whmcs/whmcs (7.2.1)
Updating dependencies
Loading composer repositories with package information

**Comment by hakanersu** [comment]
Whmcs 7+ ile Guzzle kullanmaya başlamış ancak anlaşılan oldukça eski bir versiyonunu kullanıyor ve anlaşılan update aşamasında paket kütüphanesini kullanmaya çalışıyor. Paketi whmcs versiyonu kullanacak şekilde güncelleyebilirim veya guzzle yerine standart curl kullanabilirim. Halen vakit bulamadım vakit bulduğumda test edeceğim.

**Comment by yk-labs** [comment]
hakan bey modülü kurmaya her çalıştığımda hata alıyorum. videoda anlattığınız şekilde yapmaya çalışıyorum. ancak videoda Yönlendirme Adresinin sonuna https://......./modules/addons/bulutfon/callback.php yazdığımda sayfa hata veriyor, sayfaya bağlanamıyorum. paylaştığınız modülde callback.php dosyası yok

**Comment by hakanersu** [comment]
Whmcs 7 için güncelleme yapılmıştır.
