### ISSUE TITLE
Versiyon karmaşası

### ISSUE THREAD

**Issue by muratgaygusuz** [bulutfon/bulutfon-whmcs#21]
Merhaba,
Son sürüm 1.0.3 olarak gözüküyor ancak en son sürüm 1.0.2 olarak indirilebilir durumda gözüküyor.

**Comment by hakanersu** [comment]
WHMCS 7 icin güncelleme yapıldı.

https://github.com/hakanersu/bulutfon-whmcs/releases/tag/1.1.0
