### ISSUE TITLE
1.1.0 sürümü çalışmıyor

### ISSUE THREAD

**Issue by muratgaygusuz** [bulutfon/bulutfon-whmcs#22]
Bugün eklenen 1.1.0 sürümü kurulduğunda WHMCS çöküyor. Releases kısmında yalnızca source olarak mevcut. Test ettiniz mi?

**Comment by hakanersu** [comment]
Merhaba murat bey, 7.1.x sürümüyle test edilmiştir. Releases kısmını güncelledim tekrar hata alırsanız hata kodunu lütfen buradan paylaşın.

**Comment by MtAydemir** [comment]
Evet, yenisinde bir sorun görünmüyor, ancak en son attığınız dosyalarda vendor klasörü bulunuyor. Vendor dosyaları arasındaki guzzle kütüphanesi whmcs de sorun çıkarıyor. Whmcs güncelleme yaparken dahili guzzle ile çakışma yapmaktadır. Bu versiyon curl üzerinden işlem yapıyor diye biliyordum?

**Comment by hakanersu** [comment]
@MtAydemir Anlaşılan kullandığım bulutfon sdk'sı içinde de guzzle geliyormuş. Bulutfon sdk'e bu sürümde gerek kalmadığından bir sonraki versiyonda bulutfonsdk ve ihtiyaç kalmayan birkaç paketi daha kaldıracağım.

**Comment by muratgaygusuz** [comment]
Yeni koyduğunuz dosya ile yüklediğimde hata almadan çalıştı. Kullandığım sürüm 7.3.0. Ancak @MtAydemir 'in yazdığı gibi güncelleme konusunda sıkıntı olacak. Teşekkürler.

**Comment by muratgaygusuz** [comment]
Bir önceki mesajımda çalıştığını yazmıştım. Ancak belli işlemler sonrası WHMCS çöküyor. Örneğin açılan ticket'a cevap yazıldığında WHMCS hata vermeye başlıyor. Bu yüzden eklentiyi kaldırmak zorunda kaldım.

**Comment by hakanersu** [comment]
Whmcs 7.6 uzerinde calisan uygulamalar ve yeni bir whmcs 7.6 kurulumu uzerinde testler yapilmistir. Su an icin herhangi bir problem ile karsilasmadik, hata kodlari iletilebilirse daha ayrintili bilgi vermeye calisirim.
