### ISSUE TITLE
gönderim yapılamıyor

### ISSUE THREAD

**Issue by srhnyldz** [bulutfon/bulutfon-whmcs#23]
WHMCS 7.5.2 ve PHP7.1 ile gönderim yapmıyor. Önceden PHP5.6 ile yapıyordu ama 7.1 ile göndermiyor. üstelik modül kayıtlarında bir hata mesajıda bulunmuyor.

**Comment by srhnyldz** [comment]
Komple silip tekrar yükledim eklentiyi. Artık eklentiler altında bulutfona tıklayınca meşhur Oops sayfası çıkmaya başladı :)

`
Error: Whoops\Exception\ErrorException: Class 'Xuma\Controllers\Controller' not found in /home/***/public_html/panel/modules/addons/bulutfon/controllers/HomeController.php:4 Stack trace: #0 /home/***/public_html/panel/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(1, 'Class 'Xuma\\Con...', '/home/***/pu...', 4) #1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown() #2 {main}
`

**Comment by hakanersu** [comment]
Merhaba @srhnyldz geç cevap için kusura bakma 1 hafta içinde incelemeye çalışacağım.

**Comment by srhnyldz** [comment]
@hakanersu  ayrıca whmcs 7.6.0 a güncelledik. PHP sürümü aynı. AYnı hata. Bilginiz olsun diye yazıyorum. Teşekkürler...

**Comment by hakanersu** [comment]
Merhaba @srhnyldz whmcs 7.6 sifir ve hali hazirda kullanilan bir sistem uzerinde yeniden kurulumlar denedim ancak henuz bir hata ile karsilasmadim ancak hataya bakarak **vendor** dizininin varligini kontrol ederseniz sevinirim. 

**/modules/addons/bulutfon/vendor**
